### PR TITLE
Merged search functionality from jupyter/jupyter-book

### PR DESCRIPTION
**Pull request by kysolvik**

### CODE REVIEW

**Comment by choldgraf** [comment]
hey @kysolvik would you be willing to prototype a new command-line-interface I've been playing around with for Jupyter-Book? :-)

**Comment by kysolvik** [comment]
sure thing @choldgraf! Send it my way :)

**Comment by choldgraf** [comment]
I'm working on it over here: https://github.com/jupyter/jupyter-book/pull/89

there are instructions in there for giving it a shot, I'd love feedback!

**Comment by kysolvik** [comment]
Awesome! I'm going to give it a shot today.

**Pull request merged**
