### PR TITLE
reorganizing our content

### PR DESCRIPTION
**Pull request by choldgraf**
This reorganizes the developer guide into three major sections:

1. An Author's guide (this is closer to a "developer guide"
2. An overview of the submission process
3. Guides for specific roles *within* the submission process

What do folks think about that structure? It seems a bit more nicely-structured than it was before to me.

This will break links just FYI, but I think it is OK as it'll just be a one-time switch...

Note: it doesn't really change any *content*, only the structure...we can work on the content as a next step

here's a link to the docs: https://191-165885836-gh.circle-artifacts.com/0/html/intro.html

### CODE REVIEW

**Comment by lwasser** [comment]
@choldgraf you rock. i will look more closely at this tomorrow but at first glance it already looks better + i LOVE the new jupyter book fonts. super modern and clean.
I'm curious how you are able to view html files in circle ci!! i didn't know you could do that. THANK YOU for this.

**Comment by choldgraf** [comment]
you do it with "build artifacts" - basically these are files that are generated by the build process that you can look at later on 👍

**Comment by choldgraf** [comment]
hey @lwasser do I have permission to merge some of these changes so we can make iterative progress?

**Comment by lwasser** [comment]
sorry @choldgraf please merge!!

**Comment by choldgraf** [comment]
cool! I may take a few stabs at other content as well over the week

**Comment by lwasser** [comment]
thank you @choldgraf !! much appreciated. i'm happy to help too... when we chat tomorrow maybe we can briefly chat about regrouping on funding as well :)

**Pull request merged**
