### PR TITLE
Editor Review content edits

### PR DESCRIPTION
**Pull request by lwasser**
as a part of setting up our FIRST REVIEW i am editing the dev_guide contents.
@npch @choldgraf @jlpalomino if you can do the same as you go through your review it would be wonderful.

### CODE REVIEW

**Comment by lwasser** [comment]
i'm going to merge my own PR... feel free to slap my wrist for this unless someone **really** wants to review my edits :)

**Comment by kysolvik** [comment]
Looks great to me! Thanks :)

**Comment by lwasser** [comment]
thanks @kysolvik !!
i noticed a lot of the markdown could use a bit of cleaning up... spacing and such. it would be good to work on that as well !

**Comment by kysolvik** [comment]
@lwasser sure, happy to work on cleaning it up a bit!

**Pull request merged**
